const dummyUsers = [
  {
    id: "MX69Do2ESTVpgp18XplEzvKTBCe2",
    channel: "password",
    email: "user1@example.com",
    password: "test1234!",
    name: "김철수",
    agree: true,
    birthyear: "1985",
    blog: "blog1",
    gender: "남",
    influence: "influence1",
    instagram: "insta1",
    nickname: "철수",
    phone: "01011112222",
    street: "서울 강남구 역삼로",
    zonecode: "06130",
  },
  {
    id: "ri1oT6BwBqhSPuPTIOnWcD54xIy1",
    channel: "password",
    email: "user2@example.com",
    password: "test1234!",
    name: "박영희",
    agree: true,
    birthyear: "1992",
    blog: "blog2",
    gender: "여",
    influence: "influence2",
    instagram: "insta2",
    nickname: "영희",
    phone: "01022223333",
    street: "서울 서초구 서초대로",
    zonecode: "06620",
  },
  {
    id: "03zVfZUwtvRjXyUSEh5Be6uv04o2",
    channel: "password",
    email: "user3@example.com",
    password: "test1234!",
    name: "이민호",
    agree: true,
    birthyear: "1990",
    blog: "blog3",
    gender: "남",
    influence: "influence3",
    instagram: "insta3",
    nickname: "민호",
    phone: "01033334444",
    street: "서울 송파구 올림픽로",
    zonecode: "05510",
  },
  {
    id: "SGdJKY6g9zeyEN9F3BrVdiXnhsB2",
    channel: "password",
    email: "user4@example.com",
    password: "test1234!",
    name: "최수정",
    agree: true,
    birthyear: "1995",
    blog: "blog4",
    gender: "여",
    influence: "influence4",
    instagram: "insta4",
    nickname: "수정",
    phone: "01044445555",
    street: "서울 종로구 종로",
    zonecode: "03150",
  },
  {
    id: "ahk9HDrMbqXYkmH8OQjlv4GKwjL2",
    channel: "password",
    email: "user5@example.com",
    password: "test1234!",
    name: "한동훈",
    agree: true,
    birthyear: "1988",
    blog: "blog5",
    gender: "남",
    influence: "influence5",
    instagram: "insta5",
    nickname: "동훈",
    phone: "01055556666",
    street: "서울 마포구 월드컵로",
    zonecode: "03900",
  },
  {
    id: "nKZx8pDeegYphW7jpMTAGo4h9E32",
    channel: "password",
    email: "user6@example.com",
    password: "test1234!",
    name: "김하나",
    agree: true,
    birthyear: "1993",
    blog: "blog6",
    gender: "여",
    influence: "influence6",
    instagram: "insta6",
    nickname: "하나",
    phone: "01066667777",
    street: "서울 강동구 천호대로",
    zonecode: "05330",
  },
  {
    id: "ZsRmT7gbEmQDtF4EGclyFnGwEhw1",
    channel: "password",
    email: "user7@example.com",
    password: "test1234!",
    name: "이준혁",
    agree: true,
    birthyear: "1987",
    blog: "blog7",
    gender: "남",
    influence: "influence7",
    instagram: "insta7",
    nickname: "준혁",
    phone: "01077778888",
    street: "서울 용산구 이태원로",
    zonecode: "04390",
  },
  {
    id: "f1mAsPMzfzfBjuXZzHUhOtO0J9Q2",
    channel: "password",
    email: "user8@example.com",
    password: "test1234!",
    name: "오미정",
    agree: true,
    birthyear: "1991",
    blog: "blog8",
    gender: "여",
    influence: "influence8",
    instagram: "insta8",
    nickname: "미정",
    phone: "01088889999",
    street: "서울 동작구 상도로",
    zonecode: "06930",
  },
  {
    id: "1ERoR2K6UWNWaylLFoQzyihbTOr2",
    channel: "password",
    email: "user9@example.com",
    password: "test1234!",
    name: "박준성",
    agree: true,
    birthyear: "1986",
    blog: "blog9",
    gender: "남",
    influence: "influence9",
    instagram: "insta9",
    nickname: "준성",
    phone: "01099990000",
    street: "서울 은평구 통일로",
    zonecode: "03300",
  },
  {
    id: "JCjTi0WqhsMZiFxiw0slyozZcx02",
    channel: "password",
    email: "user10@example.com",
    password: "test1234!",
    name: "김은지",
    agree: true,
    birthyear: "1989",
    blog: "blog10",
    gender: "여",
    influence: "influence10",
    instagram: "insta10",
    nickname: "은지",
    phone: "01010101010",
    street: "서울 관악구 신림로",
    zonecode: "08700",
  },
];

module.exports = { dummyUsers };
